project:
  type: website
  output-dir: docs


website:
  title: "Mel Baldino"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: currentwork.qmd
        text: Current Work
      - href: pastwork.qmd
        text: Past Work
      - href: teaching.qmd
        text: Teaching
      - href: service.qmd
        text: Service
      - href: portfolio.qmd
        text: Portfolio
      - href: news.qmd
        text: News
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

